<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.w9i1Olv' shared service.

return $this->privates['.service_locator.w9i1Olv'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('circuit' => function (): \App\Entity\Circuit {
    return ($this->privates['.errored..service_locator.w9i1Olv.App\Entity\Circuit'] ?? $this->load('getCircuitService.php'));
}));
