<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dTFn.OP' shared service.

return $this->privates['.service_locator.dTFn.OP'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('etapeRepository' => function (): \App\Repository\EtapeRepository {
    return ($this->privates['App\Repository\EtapeRepository'] ?? $this->load('getEtapeRepositoryService.php'));
}));
