<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.menu.main' shared autowired service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/ItemInterface.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/MenuItem.php';

return $this->privates['app.menu.main'] = ($this->privates['app.menu_builder'] ?? $this->load('getApp_MenuBuilderService.php'))->createMainMenu(array());
