<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.menu_builder' shared autowired service.

include_once $this->targetDirs[3].'/src/Menu/MenuBuilder.php';

return $this->privates['app.menu_builder'] = new \App\Menu\MenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), $this);
