<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFTSYcT1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFTSYcT1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFTSYcT1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFTSYcT1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFTSYcT1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FTSYcT1',
    'container.build_id' => 'b772cb33',
    'container.build_time' => 1542711888,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFTSYcT1');
