<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYkZbG7m\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYkZbG7m/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYkZbG7m.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYkZbG7m\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYkZbG7m\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YkZbG7m',
    'container.build_id' => '9de560cf',
    'container.build_time' => 1543190335,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYkZbG7m');
