<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2wlxiq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2wlxiq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO2wlxiq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO2wlxiq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerO2wlxiq\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'O2wlxiq',
    'container.build_id' => '0feb2b5b',
    'container.build_time' => 1543330336,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2wlxiq');
